Network/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Network.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Network/Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Network.Pages
{
    public class HomeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Network/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Network.Core;
using Network.Data;
using Network.Util;
using Network.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Vereyon.Web;

namespace Network.Pages
{
    public class IndexModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly NetworkDbContext _dbContext;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<IndexModel> _logger;

        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; }

        public int PageSize { get; } = 30;

        public IndexModel(SignInManager<ApplicationUser> signInManager,
            ILogger<IndexModel> logger,
            UserManager<ApplicationUser> userManager,
            NetworkDbContext dbContext)
        {
            _userManager = userManager;
            _dbContext = dbContext;
            _signInManager = signInManager;
            _logger = logger;

            PageIndex = 1;
        }

        public IActionResult OnGet()
        {
            PageIndex = Math.Max(1, PageIndex);

            return Page();
        }
    }
}

Network/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Network.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Network/Pages/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Network.Core;
using Network.Data;
using Network.Util;

namespace Network.Pages
{

    public class ProfileModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly NetworkDbContext _dbContext;
        private readonly ILogger<ProfileModel> _logger;
        public Guid? UserId { get; set; }

        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; }
        public int PageSize { get; } = 5;

        [BindProperty(SupportsGet = true)]
        public string Tab { get; set; }

        public bool IsFollowUserButtonVisible { get; set; }
        public bool IsFollowingUser { get; set; }
        public int FollowerCount { get; set; }
        public int FollowingCount { get; set; }

        public ApplicationUser ProfileUser { get; set; }

        public ProfileModel(ILogger<ProfileModel> logger,
            UserManager<ApplicationUser> userManager,
            NetworkDbContext dbContext)
        {
            _userManager = userManager;
            _dbContext = dbContext;
            _logger = logger;

            PageIndex = 1;
        }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            UserId = User.GetUserId();

            IsFollowUserButtonVisible = User.Identity.IsAuthenticated && UserId.Value != id;

            ProfileUser = await _dbContext.Users
                .Select(u => new ApplicationUser
                {
                    Id = u.Id,
                    Firstname = u.Firstname,
                    Surname = u.Surname,
                })
                .SingleOrDefaultAsync(u => u.Id == id);

            FollowerCount = await _dbContext.Follows.Where(f => f.FolloweeId == id && f.IsDeleted == false).CountAsync();
            FollowingCount = await _dbContext.Follows.Where(f => f.FollowerId == id && f.IsDeleted == false).CountAsync();

            if (IsFollowUserButtonVisible && FollowerCount > 0)
            {
                IsFollowingUser = await _dbContext.Follows
                        .AnyAsync(f => f.FolloweeId == id && f.FollowerId == UserId.Value && f.IsDeleted == false);
            }

            PageIndex = Math.Max(1, PageIndex);

            return Page();
        }

        public bool IsTabVisible(string tab)
        {
            return Tab == tab;
        }
    }
}

Network/ViewComponents/PaginatedFollowersViewComponent.cs
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Network.Core;
using Network.Data;
using Network.Util;
using Network.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Network.ViewComponents
{
    public class PaginatedFollowersViewComponent : ViewComponent
    {
        private readonly NetworkDbContext _dbContext;

        public PaginatedFollowersViewComponent(NetworkDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IQueryable<UserFollow> GetFollowers(Guid? userId)
        {
            return _dbContext.Follows.AsNoTracking()
                    .Where(f => f.FolloweeId == userId && f.IsDeleted == false)
                    .OrderByDescending(p => p.CreatedOn)
                    .Include(f => f.Follower)
                    .Select(f => new UserFollow()
                    {
                        FollowerId = f.FollowerId,
                        Follower = new ApplicationUser
                        {
                            Id = f.Follower.Id,
                            Firstname = f.Follower.Firstname,
                            Surname = f.Follower.Surname
                        }
                    });
        }

        public async Task<IViewComponentResult> InvokeAsync(int pageIndex, int pageSize, Guid userId, int? totalCount, string tab = null)
        {
            var query = GetFollowers(userId);

            var paginated = await PaginatedList<UserFollow>.CreateAsync(query, pageIndex, pageSize, totalCount);

            paginated.AdditionalQueryStrings = new Dictionary<string, string>() { { "tab", tab } };
            
            return View(paginated);
        }
    }
}

Network/ViewComponents/PaginatedFollowingViewComponent.cs
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Network.Core;
using Network.Data;
using Network.Util;
using Network.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Network.ViewComponents
{
    public class PaginatedFollowingViewComponent : ViewComponent
    {
        private readonly NetworkDbContext _dbContext;

        public PaginatedFollowingViewComponent(NetworkDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IQueryable<UserFollow> GetFollowing(Guid? userId)
        {
            return _dbContext.Follows.AsNoTracking()
                    .Where(f => f.FollowerId == userId && f.IsDeleted == false)
                    .OrderByDescending(p => p.CreatedOn)
                    .Include(f => f.Followee)
                    .Select(f => new UserFollow()
                    {
                        Followee = new ApplicationUser
                        {
                            Id = f.Followee.Id,
                            Firstname = f.Followee.Firstname,
                            Surname = f.Followee.Surname
                        }
                    });
        }


        public async Task<IViewComponentResult> InvokeAsync(int pageIndex, int pageSize, Guid userId, int? totalCount, string tab = null)
        {
            var query = GetFollowing(userId);
           
            var paginated = await PaginatedList<UserFollow>.CreateAsync(query, pageIndex, pageSize, totalCount);

            paginated.AdditionalQueryStrings = new Dictionary<string, string>() { { "tab", tab } };

            return View(paginated);
        }
    }
}

Network/ViewComponents/PaginatedPostsViewComponent.cs
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Network.Core;
using Network.Data;
using Network.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Network.ViewComponents
{
    public class PaginatedPostsViewComponent : ViewComponent
    {
        private readonly NetworkDbContext _dbContext;

        public PaginatedPostsViewComponent(NetworkDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IQueryable<Post> GetAllPosts(Guid? userId)
        {

            var predicate = PredicateBuilder.New<Post>(p => p.IsDeleted == false);

            if (userId.HasValue)
            {
                predicate.And(p => p.CreatedById == userId);
            }

            return _dbContext.Posts.AsNoTracking()
                    .Where(predicate)
                    .OrderByDescending(p => p.CreatedOn)
                    .Include(p => p.UpdatedBy)
                    .Include(p => p.Likes)
                    .Select(p => new Post
                    {
                        Id = p.Id,
                        Content = p.Content,
                        UpdatedOn = p.UpdatedOn,
                        CreatedById = p.CreatedById,
                        CreatedBy = new ApplicationUser
                        {
                            Id = p.CreatedBy.Id,
                            Firstname = p.CreatedBy.Firstname,
                            Surname = p.CreatedBy.Surname
                        },
                        // Have to do .ToList().ToHashSet() rather than ToHashSet() due to this issue - https://github.com/dotnet/efcore/issues/20101
                        LikeSet = p.Likes.Where(l => l.IsDeleted == false).Select(l => l.CreatedByUserId).ToList().ToHashSet()
                    });

        }


        public async Task<IViewComponentResult> InvokeAsync(int pageIndex, int pageSize, Guid? userId, string tab = null)
        {
            var query = GetAllPosts(userId);

            var paginated = await PaginatedList<Post>.CreateAsync(query, pageIndex, pageSize);

            paginated.AdditionalQueryStrings = new Dictionary<string, string>() { { "tab", tab } };

            return View(paginated);
        }
    }
}

Network/Pages/Home.cshtml
@page
@model Network.Pages.HomeModel
@{
    ViewData["Title"] = "Home";
}

<partial name="Post/_PostPartial" model="new Post()" />

Network/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}
<partial name="Post/_NewPostPartial" model="new Post()" />

@await Component.InvokeAsync("PaginatedPosts", new { pageIndex = Model.PageIndex, pageSize = Model.PageSize })

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Network/Pages/Profile.cshtml
@page "{id:guid}"
@model Network.Pages.ProfileModel
@{
    ViewData["Title"] = Model.ProfileUser.FullName;
}
<h2 class="mb-3">@Model.ProfileUser.FullName</h2>

@if (Model.IsFollowUserButtonVisible)
{
    <div class="mt-3 mb-3">
        @{
            var label = Model.IsFollowingUser ? "Following" : "Follow";
            var cssClass = Model.IsFollowingUser ? "btn-primary" : "btn-light";
        }
        <button type="button" class="js-follow-button btn @cssClass btn-block" data-following="@Model.IsFollowingUser" data-user-id="@Model.ProfileUser.Id">
            @label
        </button>
    </div>
}

@{
    var postTabVisible = Model.IsTabVisible("posts");
    var followersTabVisible = Model.IsTabVisible("followers");
    var followingTabVisible = Model.IsTabVisible("following");
}
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link @(postTabVisible ? "active": "")" asp-page="profile" asp-route-tab="posts" role="tab">Posts</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @(followersTabVisible ? "active": "")" asp-page="profile" asp-route-tab="followers" role="tab">
            Followers
            <span class="badge badge-info badge-pill js-followers-count">@Model.FollowerCount</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link @(followingTabVisible ? "active": "")" asp-page="profile" asp-route-tab="following" role="tab">
            Following
            <span class="badge badge-info badge-pill">@Model.FollowingCount</span>
        </a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    @if (postTabVisible)
    {
        <div>
            @await Component.InvokeAsync("PaginatedPosts", new {
               pageIndex = Model.PageIndex,
               pageSize = Model.PageSize,
               userId = Model.ProfileUser.Id,
               tab = Model.Tab
            })
        </div>
    }

    @if (followersTabVisible && Model.FollowerCount > 0)
    {
        <div>
            @await Component.InvokeAsync("PaginatedFollowers", new {
               pageIndex = Model.PageIndex,
               pageSize = Model.PageSize,
               userId = Model.ProfileUser.Id,
               totalCount = Model.FollowerCount,
               tab = Model.Tab
            })
        </div>
    }

    @if (followingTabVisible && Model.FollowingCount > 0)
    {
        <div>
            @await Component.InvokeAsync("PaginatedFollowing", new {
               pageIndex = Model.PageIndex,
               pageSize = Model.PageSize,
               userId = Model.ProfileUser.Id,
               totalCount = Model.FollowingCount,
               tab = Model.Tab
            })
        </div>
    }

</div>